name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - master
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Eller vilken version du använder
      - name: Install dependencies
        run: npm install
      - name: Setup Environment Variables
        run: |
          echo "VITE_REACT_APP_FIREBASE_API_KEY=${{ secrets.VITE_REACT_APP_FIREBASE_API_KEY }}" >> $GITHUB_ENV
          echo "VITE_REACT_APP_AUTH_DOMAIN=${{ secrets.VITE_REACT_APP_AUTH_DOMAIN }}" >> $GITHUB_ENV
          echo "VITE_REACT_APP_PROJECT_ID=${{ secrets.VITE_REACT_APP_PROJECT_ID }}" >> $GITHUB_ENV
          echo "VITE_REACT_APP_STORAGE_BUCKET=${{ secrets.VITE_REACT_APP_STORAGE_BUCKET }}" >> $GITHUB_ENV
          echo "VITE_REACT_APP_MESSAGE_SENDER_ID=${{ secrets.VITE_REACT_APP_MESSAGE_SENDER_ID }}" >> $GITHUB_ENV
          echo "VITE_REACT_APP_APP_ID=${{ secrets.VITE_REACT_APP_APP_ID }}" >> $GITHUB_ENV
      - name: Build
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_TYSKLANDREACTAPP }}
          projectId: tysklandreactapp
